COLUMN_MEANINGS = [
    {"columnName": "TBADatenID", "meaning": "Database record ID"},
    {"columnName": "EQUI", "meaning": "Equipment/machine identifier"},
    {"columnName": "LGNR", "meaning": "Location/plant identifier"},
    {"columnName": "DATUM", "meaning": "Record date/time"},
    {"columnName": "AP", "meaning": "Work-plan/process-order code"},
    {"columnName": "MASTERDAT", "meaning": "Master-data reference"},
    {"columnName": "FA", "meaning": "Administrative/process classification code"},
    {"columnName": "MATNR", "meaning": "Material/product number"},
    {"columnName": "PERS", "meaning": "Person/employee identifier"},
    {"columnName": "STK_GES", "meaning": "Total stock/count"},
    {"columnName": "STK_NIO", "meaning": "Non-conforming (failed) count"},
    {"columnName": "STK_IO", "meaning": "Conforming (passed) count"},
    {"columnName": "MD1_DREH", "meaning": "Rotation/torque-related process value"},
    {"columnName": "MD2_DREH", "meaning": "Rotation/torque-related process value"},
    {"columnName": "MD3_DREH", "meaning": "Rotation/torque-related process value"},
    {"columnName": "MD4_DREH", "meaning": "Rotation/torque-related process value"},
    {"columnName": "PD1_DREH", "meaning": "Rotation/torque-related process value"},
    {"columnName": "PD2_DREH", "meaning": "Rotation/torque-related process value"},
    {"columnName": "PD3_DREH", "meaning": "Rotation/torque-related process value"},
    {"columnName": "PD4_DREH", "meaning": "Rotation/torque-related process value"},
    {"columnName": "WUCHTVERS_ANZ", "meaning": "Number of balancing attempts"},
    {"columnName": "DAUER_PRO_ATL", "meaning": "Duration per balancing operation"},
    {"columnName": "STATUS", "meaning": "Overall status/result code"},
    {"columnName": "DOK", "meaning": "Document/reference number"},
    {
        "columnName": "MD1_ANLIEF_MG",
        "meaning": "Measured process value at input/initial point",
    },
    {
        "columnName": "MD1_ANLIEF_G",
        "meaning": "Measured process value at input/initial point",
    },
    {
        "columnName": "MD1_AUSLIEF_MG",
        "meaning": "Measured process value at output/final point",
    },
    {
        "columnName": "MD1_AUSLIEF_G",
        "meaning": "Measured process value at output/final point",
    },
    {
        "columnName": "MD2_ANLIEF_MG",
        "meaning": "Measured process value at input/initial point",
    },
    {
        "columnName": "MD2_ANLIEF_G",
        "meaning": "Measured process value at input/initial point",
    },
    {
        "columnName": "MD2_AUSLIEF_MG",
        "meaning": "Measured process value at output/final point",
    },
    {
        "columnName": "MD2_AUSLIEF_G",
        "meaning": "Measured process value at output/final point",
    },
    {
        "columnName": "MD3_ANLIEF_MG",
        "meaning": "Measured process value at input/initial point",
    },
    {
        "columnName": "MD3_ANLIEF_G",
        "meaning": "Measured process value at input/initial point",
    },
    {
        "columnName": "MD3_AUSLIEF_MG",
        "meaning": "Measured process value at output/final point",
    },
    {
        "columnName": "MD3_AUSLIEF_G",
        "meaning": "Measured process value at output/final point",
    },
    {
        "columnName": "MD4_ANLIEF_MG",
        "meaning": "Measured process value at input/initial point",
    },
    {
        "columnName": "MD4_ANLIEF_G",
        "meaning": "Measured process value at input/initial point",
    },
    {
        "columnName": "MD4_AUSLIEF_MG",
        "meaning": "Measured process value at output/final point",
    },
    {
        "columnName": "MD4_AUSLIEF_G",
        "meaning": "Measured process value at output/final point",
    },
    {
        "columnName": "EB1_ANLIEF_MG",
        "meaning": "Measured process value at input/initial point",
    },
    {
        "columnName": "EB1_ANLIEF_G",
        "meaning": "Measured process value at input/initial point",
    },
    {
        "columnName": "EB1_AUSLIEF_MG",
        "meaning": "Measured process value at output/final point",
    },
    {
        "columnName": "EB1_AUSLIEF_G",
        "meaning": "Measured process value at output/final point",
    },
    {
        "columnName": "EB2_ANLIEF_MG",
        "meaning": "Measured process value at input/initial point",
    },
    {
        "columnName": "EB2_ANLIEF_G",
        "meaning": "Measured process value at input/initial point",
    },
    {
        "columnName": "EB2_AUSLIEF_MG",
        "meaning": "Measured process value at output/final point",
    },
    {
        "columnName": "EB2_AUSLIEF_G",
        "meaning": "Measured process value at output/final point",
    },
    {
        "columnName": "PD1_ANLIEF_1_MV",
        "meaning": "Measured process value at input/initial point",
    },
    {
        "columnName": "PD1_ANLIEF_1_G",
        "meaning": "Measured process value at input/initial point",
    },
    {
        "columnName": "PD1_AUSLIEF_1_MV",
        "meaning": "Measured process value at output/final point",
    },
    {
        "columnName": "PD1_AUSLIEF_1_G",
        "meaning": "Measured process value at output/final point",
    },
    {
        "columnName": "PD2_ANLIEF_1_MV",
        "meaning": "Measured process value at input/initial point",
    },
    {
        "columnName": "PD2_ANLIEF_1_G",
        "meaning": "Measured process value at input/initial point",
    },
    {
        "columnName": "PD2_AUSLIEF_1_MV",
        "meaning": "Measured process value at output/final point",
    },
    {
        "columnName": "PD2_AUSLIEF_1_G",
        "meaning": "Measured process value at output/final point",
    },
    {
        "columnName": "PD3_ANLIEF_1_MV",
        "meaning": "Measured process value at input/initial point",
    },
    {
        "columnName": "PD3_ANLIEF_1_G",
        "meaning": "Measured process value at input/initial point",
    },
    {
        "columnName": "PD3_AUSLIEF_1_MV",
        "meaning": "Measured process value at output/final point",
    },
    {
        "columnName": "PD3_AUSLIEF_1_G",
        "meaning": "Measured process value at output/final point",
    },
    {
        "columnName": "PD4_ANLIEF_1_MV",
        "meaning": "Measured process value at input/initial point",
    },
    {
        "columnName": "PD4_ANLIEF_1_G",
        "meaning": "Measured process value at input/initial point",
    },
    {
        "columnName": "PD4_AUSLIEF_1_MV",
        "meaning": "Measured process value at output/final point",
    },
    {
        "columnName": "PD4_AUSLIEF_1_G",
        "meaning": "Measured process value at output/final point",
    },
    {"columnName": "ARBEITSGANG", "meaning": "Process operation/work step"},
    {"columnName": "KALI_LADER", "meaning": "Loader/calibration setting or value"},
    {"columnName": "OEL_DURCHFLUSS", "meaning": "Oil flow rate"},
    {"columnName": "OEL_DRUCK", "meaning": "Oil pressure"},
    {"columnName": "OEL_TEMPERATUR", "meaning": "Oil temperature"},
    {"columnName": "PF_SET", "meaning": "Press-fit setpoint"},
    {"columnName": "PF_TORQUE", "meaning": "Press-fit torque"},
    {"columnName": "PF_ANGLE", "meaning": "Press-fit angle"},
    {"columnName": "SPANN_DRUCK", "meaning": "Clamping pressure"},
    {"columnName": "Gesamtdurchlaufzeit", "meaning": "Total process/throughput time"},
    {"columnName": "System", "meaning": "System or machine-system code"},
    {"columnName": "DateTime_S5", "meaning": "Station timestamp (S5)"},
    {"columnName": "Operator_ID_S5", "meaning": "Operator identifier (S5)"},
    {"columnName": "Operator_name_S5", "meaning": "Operator name (S5)"},
    {"columnName": "Program_ID_S5", "meaning": "Machine program identifier (S5)"},
    {"columnName": "Recipe_Name_S5", "meaning": "Recipe name (S5)"},
    {"columnName": "Core_part_x", "meaning": "Process/product value: Core part x"},
    {"columnName": "Recipe_No_S5", "meaning": "Recipe number (S5)"},
    {"columnName": "Mode_Operation_S5", "meaning": "Operating mode (S5)"},
    {"columnName": "Station_ID_S5", "meaning": "Station identifier (S5)"},
    {"columnName": "CycleTime_S5", "meaning": "Station cycle time (S5)"},
    {"columnName": "Shift_No_S5", "meaning": "Shift number (S5)"},
    {"columnName": "Unique_ID_S5", "meaning": "Unique record identifier (S5)"},
    {"columnName": "Result_Overall_S5", "meaning": "Station overall result (S5)"},
    {"columnName": "Defect_Code_S5", "meaning": "Station defect code (S5)"},
    {"columnName": "Order_No_S5", "meaning": "Production order number (S5)"},
    {"columnName": "Order_Qty_S5", "meaning": "Production order quantity (S5)"},
    {"columnName": "Serial_CA", "meaning": "Process/product value: Serial CA"},
    {"columnName": "Val_Pressure_Bhsg", "meaning": "Measured value for Pressure Bhsg"},
    {"columnName": "Val_Pressure_CS", "meaning": "Measured value for Pressure CS"},
    {"columnName": "Val_Pressure_TS", "meaning": "Measured value for Pressure TS"},
    {"columnName": "Val_Filltime", "meaning": "Measured value for Filltime"},
    {"columnName": "Val_Testtime", "meaning": "Measured value for Testtime"},
    {"columnName": "Val_flow_System", "meaning": "Measured value for flow System"},
    {"columnName": "Val_flow_CS", "meaning": "Measured value for flow CS"},
    {"columnName": "Val_flow_TS", "meaning": "Measured value for flow TS"},
    {
        "columnName": "Min_Pressure_Bhsg",
        "meaning": "Process/product value: Min Pressure Bhsg",
    },
    {
        "columnName": "Max_Pressure_Bhsg",
        "meaning": "Process/product value: Max Pressure Bhsg",
    },
    {
        "columnName": "Min_Pressure_CS",
        "meaning": "Process/product value: Min Pressure CS",
    },
    {
        "columnName": "Max_Pressure_CS",
        "meaning": "Process/product value: Max Pressure CS",
    },
    {
        "columnName": "Min_Pressure_TS",
        "meaning": "Process/product value: Min Pressure TS",
    },
    {
        "columnName": "Max_Pressure_TS",
        "meaning": "Process/product value: Max Pressure TS",
    },
    {
        "columnName": "Min_flow_System",
        "meaning": "Process/product value: Min flow System",
    },
    {
        "columnName": "Max_flow_System",
        "meaning": "Process/product value: Max flow System",
    },
    {"columnName": "Min_flow_CS", "meaning": "Process/product value: Min flow CS"},
    {"columnName": "Max_flow_CS", "meaning": "Process/product value: Max flow CS"},
    {"columnName": "Min_flow_TS", "meaning": "Process/product value: Min flow TS"},
    {"columnName": "Max_flow_TS", "meaning": "Process/product value: Max flow TS"},
    {"columnName": "Auto_ID_x", "meaning": "Process/product value: Auto ID x"},
    {"columnName": "DateTime_S3", "meaning": "Station timestamp (S3)"},
    {"columnName": "Operator_ID_S3", "meaning": "Operator identifier (S3)"},
    {"columnName": "Operator_name_S3", "meaning": "Operator name (S3)"},
    {"columnName": "Program_ID_S3", "meaning": "Machine program identifier (S3)"},
    {"columnName": "Recipe_Name_S3", "meaning": "Recipe name (S3)"},
    {"columnName": "Core serial", "meaning": "Process/product value: Core serial"},
    {"columnName": "Recipe_No_S3", "meaning": "Recipe number (S3)"},
    {"columnName": "Core_part_y", "meaning": "Process/product value: Core part y"},
    {"columnName": "Mode_Operation_S3", "meaning": "Operating mode (S3)"},
    {"columnName": "Station_ID_S3", "meaning": "Station identifier (S3)"},
    {"columnName": "CycleTime_S3", "meaning": "Station cycle time (S3)"},
    {"columnName": "Shift_No_S3", "meaning": "Shift number (S3)"},
    {"columnName": "Unique_ID_S3", "meaning": "Unique record identifier (S3)"},
    {"columnName": "Result_Overall_S3", "meaning": "Station overall result (S3)"},
    {"columnName": "Defect_Code_S3", "meaning": "Station defect code (S3)"},
    {"columnName": "Order_No_S3", "meaning": "Production order number (S3)"},
    {"columnName": "Order_Qty_S3", "meaning": "Production order quantity (S3)"},
    {"columnName": "Serial_CW", "meaning": "Process/product value: Serial CW"},
    {
        "columnName": "Serial_Backplate_S3",
        "meaning": "Process/product value: Serial Backplate S3",
    },
    {
        "columnName": "Serial_Bhsg_S3",
        "meaning": "Process/product value: Serial Bhsg S3",
    },
    {
        "columnName": "Pres_Oildeflector_Oring",
        "meaning": "Oil deflector O-ring presence/check",
    },
    {"columnName": "Res_CWProfileCheck", "meaning": "CW profile check result"},
    {"columnName": "Pres_Backplate", "meaning": "Backplate presence/check"},
    {"columnName": "Pres_ShaftNut", "meaning": "Shaft nut presence/check"},
    {"columnName": "Auto_ID_y", "meaning": "Process/product value: Auto ID y"},
    {"columnName": "DateTime_S1", "meaning": "Station timestamp (S1)"},
    {"columnName": "Operator_ID_S1", "meaning": "Operator identifier (S1)"},
    {"columnName": "Operator_name_S1", "meaning": "Operator name (S1)"},
    {"columnName": "Program_ID_S1", "meaning": "Machine program identifier (S1)"},
    {"columnName": "Recipe_Name_S1", "meaning": "Recipe name (S1)"},
    {"columnName": "Core Serial", "meaning": "Process/product value: Core Serial"},
    {"columnName": "Recipe_No_S1", "meaning": "Recipe number (S1)"},
    {"columnName": "Mode_Operation_S1", "meaning": "Operating mode (S1)"},
    {"columnName": "Station_ID_S1", "meaning": "Station identifier (S1)"},
    {"columnName": "CycleTime_S1", "meaning": "Station cycle time (S1)"},
    {"columnName": "Shift_No_S1", "meaning": "Shift number (S1)"},
    {"columnName": "Unique_ID_S1", "meaning": "Unique record identifier (S1)"},
    {"columnName": "Result_Overall_S1", "meaning": "Station overall result (S1)"},
    {"columnName": "Defect_Code_S1", "meaning": "Station defect code (S1)"},
    {"columnName": "Order_No_S1", "meaning": "Production order number (S1)"},
    {"columnName": "Order_Qty_S1", "meaning": "Production order quantity (S1)"},
    {"columnName": "Serial_TW", "meaning": "Process/product value: Serial TW"},
    {"columnName": "Pres_PR_Top", "meaning": "Presence/check value for PR Top"},
    {"columnName": "Pres_PR_Bottom", "meaning": "Presence/check value for PR Bottom"},
    {
        "columnName": "Min_LVDT_Width_PR1",
        "meaning": "Process/product value: Min LVDT Width PR1",
    },
    {
        "columnName": "Val_LVDT_Width_PR1",
        "meaning": "Measured value for LVDT Width PR1",
    },
    {
        "columnName": "Max_LVDT_Width_PR1",
        "meaning": "Process/product value: Max LVDT Width PR1",
    },
    {
        "columnName": "Min_LVDT_Width_PR2",
        "meaning": "Process/product value: Min LVDT Width PR2",
    },
    {
        "columnName": "Val_LVDT_Width_PR2",
        "meaning": "Measured value for LVDT Width PR2",
    },
    {
        "columnName": "Max_LVDT_Width_PR2",
        "meaning": "Process/product value: Max LVDT Width PR2",
    },
    {"columnName": "Res_TWProfileCheck", "meaning": "TW profile check result"},
    {
        "columnName": "Serial_HSCupspring",
        "meaning": "Process/product value: Serial HSCupspring",
    },
    {
        "columnName": "Serial_Bhsg_S1",
        "meaning": "Process/product value: Serial Bhsg S1",
    },
    {"columnName": "Pres_Mandrel", "meaning": "Mandrel presence/check"},
    {"columnName": "Pres_Cupspring", "meaning": "Cup spring presence/check"},
    {"columnName": "Pick_Val_Distance_Servo1", "meaning": "Servo 1 pick distance"},
    {"columnName": "Pick_Val_Distance_Servo2", "meaning": "Servo 2 pick distance"},
    {"columnName": "Place_Val_Distance_Servo1", "meaning": "Servo 1 place distance"},
    {"columnName": "Place_Val_Distance_Servo2", "meaning": "Servo 2 place distance"},
    {
        "columnName": "Min_Val_Load_BHsg_W1",
        "meaning": "Minimum measured value for Load BHsg W1",
    },
    {
        "columnName": "Max_Val_Load_BHsg_W1",
        "meaning": "Maximum measured value for Load BHsg W1",
    },
    {
        "columnName": "Min_Val_Distance_BHsg_W1",
        "meaning": "Minimum measured value for Distance BHsg W1",
    },
    {
        "columnName": "Max_Val_Distance_BHsg_W1",
        "meaning": "Maximum measured value for Distance BHsg W1",
    },
    {
        "columnName": "Min_Val_Load_BHsg_W2",
        "meaning": "Minimum measured value for Load BHsg W2",
    },
    {
        "columnName": "Max_Val_Load_BHsg_W2",
        "meaning": "Maximum measured value for Load BHsg W2",
    },
    {
        "columnName": "Min_Val_Distance_BHsg_W2",
        "meaning": "Minimum measured value for Distance BHsg W2",
    },
    {
        "columnName": "Max_Val_Distance_BHsg_W2",
        "meaning": "Maximum measured value for Distance BHsg W2",
    },
    {
        "columnName": "Min_Val_Load_BHsg_W3",
        "meaning": "Minimum measured value for Load BHsg W3",
    },
    {
        "columnName": "Max_Val_Load_BHsg_W3",
        "meaning": "Maximum measured value for Load BHsg W3",
    },
    {
        "columnName": "Min_Val_Distance_BHsg_W3",
        "meaning": "Minimum measured value for Distance BHsg W3",
    },
    {
        "columnName": "Max_Val_Distance_BHsg_W3",
        "meaning": "Maximum measured value for Distance BHsg W3",
    },
    {
        "columnName": "Min_Val_Load_BHsg_W4",
        "meaning": "Minimum measured value for Load BHsg W4",
    },
    {
        "columnName": "Max_Val_Load_BHsg_W4",
        "meaning": "Maximum measured value for Load BHsg W4",
    },
    {
        "columnName": "Min_Val_Distance_BHsg_W4",
        "meaning": "Minimum measured value for Distance BHsg W4",
    },
    {
        "columnName": "Max_Val_Distance_BHsg_W4",
        "meaning": "Maximum measured value for Distance BHsg W4",
    },
    {
        "columnName": "Serial_Pallet_S1",
        "meaning": "Process/product value: Serial Pallet S1",
    },
    {"columnName": "Auto_ID", "meaning": "Process/product value: Auto ID"},
    {"columnName": "DateTime_S2", "meaning": "Station timestamp (S2)"},
    {"columnName": "Operator_ID_S2", "meaning": "Operator identifier (S2)"},
    {"columnName": "Operator_name_S2", "meaning": "Operator name (S2)"},
    {"columnName": "Program_ID_S2", "meaning": "Machine program identifier (S2)"},
    {"columnName": "Recipe_Name_S2", "meaning": "Recipe name (S2)"},
    {"columnName": "Core_Part", "meaning": "Process/product value: Core Part"},
    {"columnName": "Recipe_No_S2", "meaning": "Recipe number (S2)"},
    {"columnName": "Mode_Operation_S2", "meaning": "Operating mode (S2)"},
    {"columnName": "Station_ID_S2", "meaning": "Station identifier (S2)"},
    {"columnName": "CycleTime_S2", "meaning": "Station cycle time (S2)"},
    {"columnName": "Shift_No_S2", "meaning": "Shift number (S2)"},
    {"columnName": "Unique_ID_S2", "meaning": "Unique record identifier (S2)"},
    {"columnName": "Result_Overall_S2", "meaning": "Station overall result (S2)"},
    {"columnName": "Defect_Code_S2", "meaning": "Station defect code (S2)"},
    {"columnName": "Order_No_S2", "meaning": "Production order number (S2)"},
    {"columnName": "Order_Qty_S2", "meaning": "Production order quantity (S2)"},
    {
        "columnName": "Serial_Bhsg_S2",
        "meaning": "Process/product value: Serial Bhsg S2",
    },
    {"columnName": "Res_ThrustRing_Assy", "meaning": "Thrust-ring assembly result"},
    {"columnName": "Pres_ThrustRing", "meaning": "Thrust-ring presence/check"},
    {"columnName": "Pres_ThrustPlate", "meaning": "Thrust-plate presence/check"},
    {"columnName": "Res_Mandrel_Removal", "meaning": "Mandrel removal result"},
    {"columnName": "Res_ThrustPlate_Assy", "meaning": "Thrust-plate assembly result"},
    {"columnName": "Auto_ID_2", "meaning": "Process/product value: Auto ID 2"},
    {"columnName": "DateTime_S4", "meaning": "Station timestamp (S4)"},
    {"columnName": "Operator_ID_S4", "meaning": "Operator identifier (S4)"},
    {"columnName": "Operator_name_S4", "meaning": "Operator name (S4)"},
    {"columnName": "Program_ID_S4", "meaning": "Machine program identifier (S4)"},
    {"columnName": "Recipe_Name_S4", "meaning": "Recipe name (S4)"},
    {"columnName": "Core_part", "meaning": "Process/product value: Core part"},
    {"columnName": "Recipe_No_S4", "meaning": "Recipe number (S4)"},
    {"columnName": "Mode_Operation_S4", "meaning": "Operating mode (S4)"},
    {"columnName": "Station_ID_S4", "meaning": "Station identifier (S4)"},
    {"columnName": "CycleTime_S4", "meaning": "Station cycle time (S4)"},
    {"columnName": "Shift_No_S4", "meaning": "Shift number (S4)"},
    {"columnName": "Unique_ID_S4", "meaning": "Unique record identifier (S4)"},
    {"columnName": "Result_Overall_S4", "meaning": "Station overall result (S4)"},
    {"columnName": "Defect_Code_S4", "meaning": "Station defect code (S4)"},
    {"columnName": "Order_No_S4", "meaning": "Production order number (S4)"},
    {"columnName": "Order_Qty_S4", "meaning": "Production order quantity (S4)"},
    {
        "columnName": "Serial_Backplate_S4",
        "meaning": "Process/product value: Serial Backplate S4",
    },
    {
        "columnName": "Serial_Bhsg_S4",
        "meaning": "Process/product value: Serial Bhsg S4",
    },
    {"columnName": "Val_PowerFactor", "meaning": "Measured power factor"},
    {"columnName": "Val_Temp_CWHeat", "meaning": "Measured CW heat temperature"},
    {"columnName": "Val_CWHeat_Cycletime", "meaning": "CW heat cycle time"},
    {
        "columnName": "CW_Pick_Val_Distance_Servo1",
        "meaning": "CW process value: Pick Val Distance Servo1",
    },
    {
        "columnName": "CW_Pick_Val_Distance_Servo2",
        "meaning": "CW process value: Pick Val Distance Servo2",
    },
    {
        "columnName": "CW_Place_HIM_Val_Distance_Servo1",
        "meaning": "CW process value: Place HIM Val Distance Servo1",
    },
    {
        "columnName": "CW_Place_HIM_Val_Distance_Servo2",
        "meaning": "CW process value: Place HIM Val Distance Servo2",
    },
    {
        "columnName": "CW_Place_TW_Val_Distance_Servo1",
        "meaning": "CW process value: Place TW Val Distance Servo1",
    },
    {
        "columnName": "CW_Place_TW_Val_Distance_Servo2",
        "meaning": "CW process value: Place TW Val Distance Servo2",
    },
    {
        "columnName": "Pick_SN_Val_Distance_Servo1",
        "meaning": "Process/product value: Pick SN Val Distance Servo1",
    },
    {
        "columnName": "Place_SN_Val_Distance_Servo1",
        "meaning": "Process/product value: Place SN Val Distance Servo1",
    },
    {
        "columnName": "Min_Val_Load_CW_W1",
        "meaning": "Minimum measured value for Load CW W1",
    },
    {
        "columnName": "Max_Val_Load_CW_W1",
        "meaning": "Maximum measured value for Load CW W1",
    },
    {
        "columnName": "Min_Val_Distance_CW_W1",
        "meaning": "Minimum measured value for Distance CW W1",
    },
    {
        "columnName": "Max_Val_Distance_CW_W1",
        "meaning": "Maximum measured value for Distance CW W1",
    },
    {
        "columnName": "Min_Val_Load_CW_W2",
        "meaning": "Minimum measured value for Load CW W2",
    },
    {
        "columnName": "Max_Val_Load_CW_W2",
        "meaning": "Maximum measured value for Load CW W2",
    },
    {
        "columnName": "Min_Val_Distance_CW_W2",
        "meaning": "Minimum measured value for Distance CW W2",
    },
    {
        "columnName": "Max_Val_Distance_CW_W2",
        "meaning": "Maximum measured value for Distance CW W2",
    },
    {
        "columnName": "Min_Val_Load_CW_W3",
        "meaning": "Minimum measured value for Load CW W3",
    },
    {
        "columnName": "Max_Val_Load_CW_W3",
        "meaning": "Maximum measured value for Load CW W3",
    },
    {
        "columnName": "Min_Val_Distance_CW_W3",
        "meaning": "Minimum measured value for Distance CW W3",
    },
    {
        "columnName": "Max_Val_Distance_CW_W3",
        "meaning": "Maximum measured value for Distance CW W3",
    },
    {
        "columnName": "Min_Val_Load_CW_W4",
        "meaning": "Minimum measured value for Load CW W4",
    },
    {
        "columnName": "Max_Val_Load_CW_W4",
        "meaning": "Maximum measured value for Load CW W4",
    },
    {
        "columnName": "Min_Val_Distance_CW_W4",
        "meaning": "Minimum measured value for Distance CW W4",
    },
    {
        "columnName": "Max_Val_Distance_CW_W4",
        "meaning": "Maximum measured value for Distance CW W4",
    },
    {
        "columnName": "Min_Val_Distance_Servo_S4",
        "meaning": "Minimum measured value for Distance Servo S4",
    },
    {
        "columnName": "Max_Val_Distance_Servo_S4",
        "meaning": "Maximum measured value for Distance Servo S4",
    },
    {
        "columnName": "Min_Val_PreTrq_Shaftnut",
        "meaning": "Minimum measured value for PreTrq Shaftnut",
    },
    {"columnName": "Val_PreTrq_Shaftnut", "meaning": "Measured shaft-nut pre-torque"},
    {
        "columnName": "Max_Val_PreTrq_Shaftnut",
        "meaning": "Maximum measured value for PreTrq Shaftnut",
    },
    {
        "columnName": "Val_PreTrqAng_Shaftnut",
        "meaning": "Measured shaft-nut pre-torque angle",
    },
    {"columnName": "Torque_Retry_Count", "meaning": "Number of torque retries"},
    {"columnName": "Auto_ID_3", "meaning": "Process/product value: Auto ID 3"},
]
